# Generated by Django 3.2.6 on 2022-07-10 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 7, 10), verbose_name='Todays Date')),
                ('sensor', models.CharField(default='LIN_ACC', max_length=100, verbose_name='Sensor Type')),
                ('x', models.FloatField(verbose_name='X ACC')),
                ('y', models.FloatField(verbose_name='Y ACC')),
                ('z', models.FloatField(verbose_name='Z ACC')),
            ],
        ),
    ]
