# Generated by Django 3.2.6 on 2022-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stoppage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc_data',
            name='timestamp',
            field=models.CharField(default='LIN_ACC', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='acc_data',
            name='date',
            field=models.CharField(default='Today', max_length=20, verbose_name='Todays Date'),
        ),
    ]
