# Generated by Django 3.2.6 on 2022-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stoppage', '0002_auto_20220710_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loc_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='Today', max_length=20, verbose_name='Todays Date')),
                ('timestamp', models.CharField(default='LIN_ACC', max_length=100, verbose_name='')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
        ),
    ]
